spring.application.name=recetasbackend
spring.datasource.url=jdbc:postgresql://localhost:5432/comida
spring.datasource.username=postgres
spring.datasource.password=admin
server.port=8080
openai.api.key=${OPENAI_API_KEY}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
